# Generated by Django 5.2.17 on 2026-08-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('medication', '복약·영양제'), ('mindfulness', '명상·스트레칭')], max_length=12)),
                ('label', models.CharField(help_text='예: 칼슘 영양제, 저녁 스트레칭', max_length=32)),
                ('time', models.TimeField(help_text='매일 반복되는 알림 시각')),
                ('is_active', models.BooleanField(default=True, help_text='끄면 오늘의 알림 목록에서 빠짐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리마인더',
                'verbose_name_plural': '리마인더',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='완료 처리한 날짜 (Asia/Seoul 기준)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='notifications.reminder')),
            ],
            options={
                'verbose_name': '리마인더 완료 기록',
                'verbose_name_plural': '리마인더 완료 기록',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_4af514_idx'),
        ),
        migrations.AddConstraint(
            model_name='remindercompletion',
            constraint=models.UniqueConstraint(fields=('reminder', 'date'), name='unique_completion_per_day'),
        ),
    ]
