# Generated by Django 5.2.17 on 2026-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=60)),
                ('total_seconds', models.PositiveSmallIntegerField(help_text='steps 초 합계 (프론트에서 다시 계산 안 해도 되게)')),
                ('steps', models.JSONField(help_text='[{"instruction": "목을 천천히 오른쪽으로 기울여요", "seconds": 20}, ...] 순서대로 진행')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='목록 정렬 순서')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '명상·스트레칭 세션',
                'verbose_name_plural': '명상·스트레칭 세션',
                'ordering': ['order'],
            },
        ),
    ]
