# Generated by Django 5.2.17 on 2026-08-19 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenopauseSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField(choices=[(0, '생리 주기가 불규칙해지기 시작했어요'), (1, '생리가 완전히 멈춘 지 1년이 넘었어요'), (2, '완경 이후 몇 년이 지났어요'), (3, '잘 모르겠어요 / 해당 사항 없음')])),
                ('stage', models.CharField(choices=[('peri', '완경 이행기'), ('menopause', '완경'), ('post', '완경 후기'), ('unknown', '판정 불가')], max_length=16)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menopause_survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
