# Generated by Django 5.2.17 on 2026-08-06 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_analysis/%Y/%m/%d/')),
                ('redness_score', models.FloatField(help_text='0~100, 높을수록 홍조가 심함')),
                ('severity', models.CharField(choices=[('normal', '정상'), ('mild', '경미'), ('moderate', '중등도'), ('severe', '심함')], max_length=10)),
                ('region_scores', models.JSONField(default=dict, help_text='부위별 홍조 점수 (forehead / left_cheek / right_cheek / nose)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
