# Generated by Django 5.2.17 on 2026-08-08 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('vasomotor', '혈관운동'), ('sleep', '수면'), ('mood', '감정'), ('physical', '신체')], max_length=16)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='앱 버튼 정렬 순서')),
                ('is_active', models.BooleanField(default=True, help_text='끄면 앱 버튼 목록에서 빠짐 (이미 쌓인 기록은 그대로 유지)')),
            ],
            options={
                'verbose_name': '증상 종류',
                'verbose_name_plural': '증상 종류',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='체크인 대상 날짜 (Asia/Seoul 기준)')),
                ('sleep_quality', models.PositiveSmallIntegerField(choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='어젯밤 잘 주무셨나요')),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='오늘 기분')),
                ('fatigue', models.PositiveSmallIntegerField(blank=True, choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='높을수록 덜 피곤함', null=True)),
                ('stress', models.PositiveSmallIntegerField(blank=True, choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='높을수록 스트레스가 적음', null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 체크인',
                'verbose_name_plural': '일일 체크인',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_checkin_per_day')],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, '가벼움'), (2, '보통'), (3, '심함')], default=2)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='증상이 있었던 시각. 원터치 기록이면 버튼을 누른 시각과 같다.')),
                ('memo', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', '앱에서 직접 기록'), ('chat', '챗봇 대화 중 기록'), ('backfill', '지난 날 소급 기록'), ('seed', '시연용 목업')], default='manual', help_text='사용자가 직접 누른 기록인지, 챗봇이 대화로 받아낸 기록인지 구분', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
                ('symptom_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='symptoms.symptomtype')),
            ],
            options={
                'verbose_name': '증상 기록',
                'verbose_name_plural': '증상 기록',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='symptoms_sy_user_id_4702d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='해당 주의 월요일')),
                ('stats', models.JSONField(default=dict, help_text='증상별 횟수·시간대 분포·지난주 대비 증감 등')),
                ('summary_text', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주간 리포트',
                'verbose_name_plural': '주간 리포트',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_report_per_week')],
            },
        ),
    ]
