# Generated by Django 5.2.17 on 2026-08-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_seed_symptom_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='time_estimated',
            field=models.BooleanField(default=False, help_text='시각을 특정하지 못해 채워 넣은 기록(주로 챗봇 소급 입력). "주로 저녁 시간대" 같은 시간대 집계에서 제외된다.'),
        ),
    ]
