# Generated by Django 5.2.17 on 2026-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_symptomlog_time_estimated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='오늘 기분', null=True),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='sleep_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], help_text='어젯밤 잘 주무셨나요', null=True),
        ),
    ]
